server: 
 port: 8081
 error: 
  include-binding-errors: always
  include-message: always
  include-exception: true
  
spring:
  
 main:
  allow-circular-references: true # 8 ve 9 yeni eklendi
 jackson: 
  serialization: 
   write-dates-as-timestamps: false
 datasource:
  hikari:
   autoCommit : false
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: password
  driver-class-name: org.postgresql.Driver
  
 jpa:
  hibernate: 
   ddl-auto: update
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  properties:
   '[hibernate.format_sql]': true
   
 #image
 servlet: 
  multipart: 
   max-file-size: 5MB
   max-request-size: 5MB
 mail: 
  host: smtp.gmail.com
  port: 587
  username: Example@gmail.com
  password: ExamplePassword
  properties: 
   mail: 
    smtp: 
     auth: true
     starttls: 
      enable: true
   
logging: 
 file: 
  name: log/chat_project_backEnd.log
 pattern:
#  console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file: "%d %-5level [%thread] %logger:%msg%n"
 level: 
  root : WARN # burasi info yerine WARN vardi degistir sonra
  '[org.springframework.web]' : DEBUG # burasi DEBUG yerine WARN vardi
  '[org.hibernate]' : INFO # burasi INFO yerine WARN vardi
  '[com.erdal.furkanVakfi]' : DEBUG
  '[org.furkanVakfi]' : DEBUG
  '[org.springframework.security]': DEBUG
  # secretkey
furkanVakfiChat :
 app :
  jwtSecret: furkanVakfiChat@!Aylaadem233
  jwtExpirationMs: 86400000 #bu rakam bir gune tekabul ediyor yani 24saat/milisanie
  
#actuator deneme 
management: 
 endpoints: 
  web: 
   exposure: 
    include: '*'
 info: 
  env: 
   enabled: true
 endpoint: 
  health: 
   show-details: always
  shutdown: 
   enabled: true

info: 
 application: 
  name: 'FurkanVakfi Sohbet App'
  description: 'This is furkan-vakfi Backend  chat Project'
  version: '@project.version@'
  